# The URL the site will be built for
base_url = "https://assured-training.org/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Put all your custom variables here
site_title = "Assured project"
site_logo = "assets/logo.svg"
site_logo_alt = "Assured logo"
site_logo_sr = "Assured project"
site_tagline = "Safe research by safe people"
copyright = "2024&ndash; Assured collaboration. All rights reserved."
header_cta = "Contact us"
header_cta_href = "contact"
