[[institution]]
name = "GESIS"
image = "gesis.svg"

[[institution]]
name = "KONSORT-SWD"
image = "konsort-swd.svg"

[[institution]]
name = "German Human Genome-Phenome Archive"
image = "ghga.svg"

[[institution]]
name = "BERD@NFDI"
image = "berd.svg"

[[institution]]
name = "Ludwig Maximilian University of Munich"
image = "lmu.svg"

[[institution]]
name = "Bundesbank"
image = "bundesbank.svg"

[[institution]]
name = "University of the West of England"
image = "uwe.svg"
