[[accordion]]
visible = "What are the benefits of using ASSURED?"
hidden = "ASSURED promotes FAIR practices for safe data use and sharing, supports improving security models, builds trust, and fosters career development within the research data sector."

[[accordion]]
visible = "How do I get started?"
hidden = "Access the e-learning platform at https://platform.assured-training.org/ and log in with your credentials. A user account is typically provided by email. Start with the module 'course introduction'. For account creation, contact info@assured-training.org."

[[accordion]]
visible = "How is the training structured?"
hidden = "ASSURED is modular and tailored to your role. Core modules are mandatory and cover essential knowledge. Specialised modules are mandatory or recommended depending on required skills."

[[accordion]]
visible = "How can I enroll in a module?"
hidden = "Self-enrollment is not yet available. You will be enrolled in courses defined by your institution. For additional modules, contact info@assured-training.org."

[[accordion]]
visible = "How long does it take to complete a module?"
hidden = "Each module is a microlearning unit of 5–15 minutes plus a short video (~10 minutes) and quick assessment (5–10 minutes)."

[[accordion]]
visible = "Are there deadlines for completing the training?"
hidden = "ASSURED training is self-paced. Deadlines may be set by your institution or yourself depending on objectives."

[[accordion]]
visible = "What kind of support is available if I have questions about the module content?"
hidden = "Use the messaging function within the platform or email info@assured-training.org."

[[accordion]]
visible = "What if I encounter technical issues during the training?"
hidden = "Report issues to info@assured-training.org with a clear description, steps to reproduce, error messages, and screenshots if possible."

[[accordion]]
visible = "How do I receive my certificate?"
hidden = "[Tbd – currently only a certificate of completion via Moodle?]"

[[accordion]]
visible = "Are the certificates accredited?"
hidden = "[Tbd – mention recognition from our institutions and eventually other NFDIs in the meantime?]"

[[accordion]]
visible = "How can I provide feedback on the service?"
hidden = "Send feedback via info@assured-training.org or use the feedback survey on the 'Home' page of the learning platform."
