[[accordion]]
type = "header"
visible = "General Topics"

[[accordion]]
visible = "What is ASSURED?"
hidden = "ASSURED certifies researchers as well as users and staff of Research Data Centers (RDC) by providing training for the safe and ethical use of sensitive, potentially disclosive data."

[[accordion]]
visible = "Who is ASSURED training for?"
hidden = """ASSURED training is designed for

- researchers requiring skills to responsibly use sensitive data (e.g. researchers wishing to access sensitive data held under controlled access conditions).
- data professionals working in Research Data Centers (RDC), Trusted Research Environments (TRE), Secure Processing Environments (SPE), etc. that want to gain acknowledgement for their expertise and to develop their careers.
- institutions wanting to streamline the access to their sensitive data or wanting to train and develop their team."""

[[accordion]]
visible = "What kind of training does the ASSURED project offer?"
hidden = "ASSURED is a modular, interactive, online training on sensitive data, implemented in Moodle for self-learning at one’s own pace. It equips researchers and data professionals to handle sensitive data responsibly and helps institutions improve onboarding processes, user support, and staff development, aligning with the EU Data Strategy."

[[accordion]]
visible = "What topics does the training cover?"
hidden = """The training distinguishes between core modules and specialised modules.

- Core modules cover essential knowledge such as data ethics, data citation, lawful data sharing, understanding data access, and how to produce non-disclosive research outputs.
- Specialised modules provide skills for particular roles or specific applications such as conducting research in a particular secure environment or using certain data types.

See the list of available modules on our e-learning platform: <a href="https://platform.assured-training.org//">https://platform.assured-training.org/</a>"""

[[accordion]]
visible = "Can I suggest new training topics?"
hidden = """Yes, we continually develop and enrich training according to community needs. Contact info@assured-training.org with suggestions.

- Are you an expert in a role or domain and want to contribute? Please reach out.
- Do you offer a service and want to train users or staff? We can create a specialised module and learning pathway for your target group."""

[[accordion]]
visible = "Who is responsible for the content?"
hidden = """ASSURED’s core team is an interdisciplinary group of experts covering secure data access, data ethics and governance, statistical disclosure control, data science and survey quality, educational resources and learning environments. They coordinate and deliver training, develop content, ensure quality standards, and offer consultation.

Contributors and consultors from the NFDI Consortia, the German Data Competence Centre landscape, and international institutions such as the University of West of England create and review content and assess services."""

[[accordion]]
visible = "Does ASSURED offer corporate training solutions?"
hidden = "Yes, ASSURED is a data governance training suitable for institutions handling sensitive data. The flexible, modular approach allows a customised learning pathway tailored to your institution."

[[accordion]]
visible = "How can I book ASSURED training to train and develop my team?"
hidden = """Please contact <a href="mailto:info@assured-training.org">info@assured-training.org</a> to book ASSURED’s services."""


[[accordion]]
type = "header"
visible = "Using ASSURED"

[[accordion]]
visible = "What are the benefits of using ASSURED?"
hidden = "ASSURED promotes FAIR practices for safe data use and sharing, supports improving security models, builds trust, and fosters career development within the research data sector."

[[accordion]]
visible = "How do I get started?"
hidden = """Access the e-learning platform at <a href="https://platform.assured-training.org/">https://platform.assured-training.org/</a> and log in with your credentials. A user account is typically provided by email. Start with the module 'course introduction'. For account creation, <a href="mailto:info@assured-training.org">info@assured-training.org</a>."""

[[accordion]]
visible = "How is the training structured?"
hidden = "ASSURED is modular and tailored to your role. Core modules are mandatory and cover essential knowledge. Specialised modules are mandatory or recommended depending on required skills."

[[accordion]]
visible = "How can I enroll in a module?"
hidden = """Self-enrollment is not yet available. You will be enrolled in courses defined by your institution. For additional modules, contact <a href="mailto:info@assured-training.org">info@assured-training.org</a>."""

[[accordion]]
visible = "How long does it take to complete a module?"
hidden = "Each module is a microlearning unit of 5–15 minutes plus a short video (~10 minutes) and quick assessment (5–10 minutes)."

[[accordion]]
visible = "Are there deadlines for completing the training?"
hidden = "ASSURED training is self-paced. Deadlines may be set by your institution or yourself depending on objectives."

[[accordion]]
visible = "What kind of support is available if I have questions about the module content?"
hidden = """Use the messaging function within the platform or email <a href="mailto:info@assured-training.org">info@assured-training.org</a>."""

[[accordion]]
visible = "What if I encounter technical issues during the training?"
hidden = """Report issues to <a href="mailto:info@assured-training.org">info@assured-training.org</a> with a clear description, steps to reproduce, error messages, and screenshots if possible."""

[[accordion]]
visible = "How can I provide feedback on the service?"
hidden = """Send feedback via <a href="mailto:info@assured-training.org">info@assured-training.org</a> or use the feedback survey on the <a href="https://platform.assured-training.org/">Home</a> page of the learning platform."""


[[accordion]]
type = "header"
visible = "Data Security and Protection"

[[accordion]]
visible = "How does ASSURED protect my personal information?"
hidden = """Website: see <a href="https://assured-training.org/privacy/">https://assured-training.org/privacy/</a>

Email: Messages to <a href="mailto:info@assured-training.org">info@assured-training.org</a> are stored within Roundcube Webmail (<a href="https://roundcube.net/about/">https://roundcube.net/about/</a>) under Article 6 (1) f) GDPR.

E-learning platform: Hosted by eLeDia (Germany). ASSURED uses Moodle’s privacy features (<a href="https://moodle.com/privacy-notice/">https://moodle.com/privacy-notice/</a>), secure passwords, multi-factor authentication, and role-based access control. Administrators monitor activity to detect and prevent breaches.

Learn more here: <a href="https://assured-training.org/privacy/">https://assured-training.org/privacy/</a>."""

[[accordion]]
visible = "What is ASSURED’s privacy policy?"
hidden = """Learn how ASSURED safeguards your personal data here: <a href="https://assured-training.org/privacy/">https://assured-training.org/privacy/</a>. Moodle privacy notice: <a href="https://moodle.com/de/datenschutzerklarung/">https://moodle.com/de/datenschutzerklarung/</a>"""

[[accordion]]
visible = "Is my learning progress and data kept private?"
hidden = """ASSURED uses an Authorisation and Authentication Infrastructure (AAI) to control and regulate data access and sharing. See <a href="https://assured-training.org/imprint/">https://assured-training.org/imprint/</a> for details."""
