[[accordion]]
visible = "What is ASSURED?"
hidden = "ASSURED certifies researchers as well as users and staff of Research Data Centers (RDC) by providing training for the safe and ethical use of sensitive, potentially disclosive data."

[[accordion]]
visible = "Who is ASSURED training for?"
hidden = """ASSURED training is designed for

- researchers requiring skills to responsibly use sensitive data (e.g. researchers wishing to access sensitive data held under controlled access conditions).
- data professionals working in Research Data Centers (RDC), Trusted Research Environments (TRE), Secure Processing Environments (SPE), etc. that want to gain acknowledgement for their expertise and to develop their careers.
- institutions wanting to streamline the access to their sensitive data or wanting to train and develop their team."""

[[accordion]]
visible = "What kind of training does the ASSURED project offer?"
hidden = "ASSURED is a modular, interactive, online training on sensitive data, implemented in Moodle for self-learning at one’s own pace. It equips researchers and data professionals to handle sensitive data responsibly and helps institutions improve onboarding processes, user support, and staff development, aligning with the EU Data Strategy."

[[accordion]]
visible = "What topics does the training cover?"
hidden = """The training distinguishes between core modules and specialised modules.

- Core modules cover essential knowledge such as data ethics, data citation, lawful data sharing, understanding data access, and how to produce non-disclosive research outputs.
- Specialised modules provide skills for particular roles or specific applications such as conducting research in a particular secure environment or using certain data types.

See the list of available modules on our e-learning platform: https://platform.assured-training.org/"""

[[accordion]]
visible = "Can I suggest new training topics?"
hidden = """Yes, we continually develop and enrich training according to community needs. Contact info@assured-training.org with suggestions.

- Are you an expert in a role or domain and want to contribute? Please reach out.
- Do you offer a service and want to train users or staff? We can create a specialised module and learning pathway for your target group."""

[[accordion]]
visible = "Who is responsible for the content?"
hidden = """ASSURED’s core team is an interdisciplinary group of experts covering secure data access, data ethics and governance, statistical disclosure control, data science and survey quality, educational resources and learning environments. They coordinate and deliver training, develop content, ensure quality standards, and offer consultation.

Contributors and consultors from the NFDI Consortia, the German Data Competence Centre landscape, and international institutions such as the University of West of England create and review content and assess services."""

[[accordion]]
visible = "Does ASSURED offer corporate training solutions?"
hidden = "Yes, ASSURED is a data governance training suitable for institutions handling sensitive data. The flexible, modular approach allows a customised learning pathway tailored to your institution."

[[accordion]]
visible = "How can I book ASSURED training to train and develop my team?"
hidden = "Please contact info@assured-training.org to book ASSURED’s services."
